/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SparkRouteImport } from './routes/spark'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PuzzlesRouteImport } from './routes/puzzles'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as PassportRouteImport } from './routes/passport'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MatchesRouteImport } from './routes/matches'
import { Route as ManageSubscriptionRouteImport } from './routes/manage-subscription'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GamesRouteImport } from './routes/games'
import { Route as GameRouteImport } from './routes/game'
import { Route as DatePlanRouteImport } from './routes/date-plan'
import { Route as ContactShareRouteImport } from './routes/contact-share'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as ChallengesRouteImport } from './routes/challenges'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SparkRoute = SparkRouteImport.update({
  id: '/spark',
  path: '/spark',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PuzzlesRoute = PuzzlesRouteImport.update({
  id: '/puzzles',
  path: '/puzzles',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const PassportRoute = PassportRouteImport.update({
  id: '/passport',
  path: '/passport',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesRoute = MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageSubscriptionRoute = ManageSubscriptionRouteImport.update({
  id: '/manage-subscription',
  path: '/manage-subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const GameRoute = GameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => rootRouteImport,
} as any)
const DatePlanRoute = DatePlanRouteImport.update({
  id: '/date-plan',
  path: '/date-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactShareRoute = ContactShareRouteImport.update({
  id: '/contact-share',
  path: '/contact-share',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesRoute = ChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/challenges': typeof ChallengesRoute
  '/chat': typeof ChatRoute
  '/checkout': typeof CheckoutRoute
  '/contact-share': typeof ContactShareRoute
  '/date-plan': typeof DatePlanRoute
  '/game': typeof GameRoute
  '/games': typeof GamesRoute
  '/login': typeof LoginRoute
  '/manage-subscription': typeof ManageSubscriptionRoute
  '/matches': typeof MatchesRoute
  '/onboarding': typeof OnboardingRoute
  '/passport': typeof PassportRoute
  '/premium': typeof PremiumRoute
  '/puzzles': typeof PuzzlesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/results': typeof ResultsRoute
  '/safety': typeof SafetyRoute
  '/signup': typeof SignupRoute
  '/spark': typeof SparkRoute
  '/terms': typeof TermsRoute
  '/verify': typeof VerifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/challenges': typeof ChallengesRoute
  '/chat': typeof ChatRoute
  '/checkout': typeof CheckoutRoute
  '/contact-share': typeof ContactShareRoute
  '/date-plan': typeof DatePlanRoute
  '/game': typeof GameRoute
  '/games': typeof GamesRoute
  '/login': typeof LoginRoute
  '/manage-subscription': typeof ManageSubscriptionRoute
  '/matches': typeof MatchesRoute
  '/onboarding': typeof OnboardingRoute
  '/passport': typeof PassportRoute
  '/premium': typeof PremiumRoute
  '/puzzles': typeof PuzzlesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/results': typeof ResultsRoute
  '/safety': typeof SafetyRoute
  '/signup': typeof SignupRoute
  '/spark': typeof SparkRoute
  '/terms': typeof TermsRoute
  '/verify': typeof VerifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/challenges': typeof ChallengesRoute
  '/chat': typeof ChatRoute
  '/checkout': typeof CheckoutRoute
  '/contact-share': typeof ContactShareRoute
  '/date-plan': typeof DatePlanRoute
  '/game': typeof GameRoute
  '/games': typeof GamesRoute
  '/login': typeof LoginRoute
  '/manage-subscription': typeof ManageSubscriptionRoute
  '/matches': typeof MatchesRoute
  '/onboarding': typeof OnboardingRoute
  '/passport': typeof PassportRoute
  '/premium': typeof PremiumRoute
  '/puzzles': typeof PuzzlesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/results': typeof ResultsRoute
  '/safety': typeof SafetyRoute
  '/signup': typeof SignupRoute
  '/spark': typeof SparkRoute
  '/terms': typeof TermsRoute
  '/verify': typeof VerifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/challenges'
    | '/chat'
    | '/checkout'
    | '/contact-share'
    | '/date-plan'
    | '/game'
    | '/games'
    | '/login'
    | '/manage-subscription'
    | '/matches'
    | '/onboarding'
    | '/passport'
    | '/premium'
    | '/puzzles'
    | '/reset-password'
    | '/results'
    | '/safety'
    | '/signup'
    | '/spark'
    | '/terms'
    | '/verify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/challenges'
    | '/chat'
    | '/checkout'
    | '/contact-share'
    | '/date-plan'
    | '/game'
    | '/games'
    | '/login'
    | '/manage-subscription'
    | '/matches'
    | '/onboarding'
    | '/passport'
    | '/premium'
    | '/puzzles'
    | '/reset-password'
    | '/results'
    | '/safety'
    | '/signup'
    | '/spark'
    | '/terms'
    | '/verify'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/challenges'
    | '/chat'
    | '/checkout'
    | '/contact-share'
    | '/date-plan'
    | '/game'
    | '/games'
    | '/login'
    | '/manage-subscription'
    | '/matches'
    | '/onboarding'
    | '/passport'
    | '/premium'
    | '/puzzles'
    | '/reset-password'
    | '/results'
    | '/safety'
    | '/signup'
    | '/spark'
    | '/terms'
    | '/verify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ChallengesRoute: typeof ChallengesRoute
  ChatRoute: typeof ChatRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactShareRoute: typeof ContactShareRoute
  DatePlanRoute: typeof DatePlanRoute
  GameRoute: typeof GameRoute
  GamesRoute: typeof GamesRoute
  LoginRoute: typeof LoginRoute
  ManageSubscriptionRoute: typeof ManageSubscriptionRoute
  MatchesRoute: typeof MatchesRoute
  OnboardingRoute: typeof OnboardingRoute
  PassportRoute: typeof PassportRoute
  PremiumRoute: typeof PremiumRoute
  PuzzlesRoute: typeof PuzzlesRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ResultsRoute: typeof ResultsRoute
  SafetyRoute: typeof SafetyRoute
  SignupRoute: typeof SignupRoute
  SparkRoute: typeof SparkRoute
  TermsRoute: typeof TermsRoute
  VerifyRoute: typeof VerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spark': {
      id: '/spark'
      path: '/spark'
      fullPath: '/spark'
      preLoaderRoute: typeof SparkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/puzzles': {
      id: '/puzzles'
      path: '/puzzles'
      fullPath: '/puzzles'
      preLoaderRoute: typeof PuzzlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passport': {
      id: '/passport'
      path: '/passport'
      fullPath: '/passport'
      preLoaderRoute: typeof PassportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage-subscription': {
      id: '/manage-subscription'
      path: '/manage-subscription'
      fullPath: '/manage-subscription'
      preLoaderRoute: typeof ManageSubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game': {
      id: '/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof GameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/date-plan': {
      id: '/date-plan'
      path: '/date-plan'
      fullPath: '/date-plan'
      preLoaderRoute: typeof DatePlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-share': {
      id: '/contact-share'
      path: '/contact-share'
      fullPath: '/contact-share'
      preLoaderRoute: typeof ContactShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges': {
      id: '/challenges'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof ChallengesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ChallengesRoute: ChallengesRoute,
  ChatRoute: ChatRoute,
  CheckoutRoute: CheckoutRoute,
  ContactShareRoute: ContactShareRoute,
  DatePlanRoute: DatePlanRoute,
  GameRoute: GameRoute,
  GamesRoute: GamesRoute,
  LoginRoute: LoginRoute,
  ManageSubscriptionRoute: ManageSubscriptionRoute,
  MatchesRoute: MatchesRoute,
  OnboardingRoute: OnboardingRoute,
  PassportRoute: PassportRoute,
  PremiumRoute: PremiumRoute,
  PuzzlesRoute: PuzzlesRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ResultsRoute: ResultsRoute,
  SafetyRoute: SafetyRoute,
  SignupRoute: SignupRoute,
  SparkRoute: SparkRoute,
  TermsRoute: TermsRoute,
  VerifyRoute: VerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
