// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function readSupabaseConfig() {
  const url = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const publishableKey = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;
  const missing = [
    ...(!url ? ['SUPABASE_URL'] : []),
    ...(!publishableKey ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
  ];

  return {
    url,
    publishableKey,
    error: missing.length
      ? `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`
      : null,
  };
}

const supabaseConfig = readSupabaseConfig();

export function getSupabaseConfigError() {
  return supabaseConfig.error;
}

function createSupabaseClient() {
  if (supabaseConfig.error || !supabaseConfig.url || !supabaseConfig.publishableKey) {
    const message = supabaseConfig.error ?? 'Missing Supabase configuration.';
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(supabaseConfig.url, supabaseConfig.publishableKey, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

